/**
 * Cleans assistant messages by removing technical blocks (JSON, headers) 
 * to provide a clean conversational experience.
 */
export const cleanAssistantMessage = (content: string): string => {
    if (!content) return '';

    // 1. Remove JSON code blocks (allow optional 'json')
    let cleaned = content.replace(/```(?:json)?[\s\S]*?```/g, '');
    
    // 2. Remove other generic code blocks if they look like data
    cleaned = cleaned.replace(/```[\s\S]*?```/g, (match) => {
        // If it's a very short code block or contains common dialogue, keep it
        if (match.length < 50 || match.includes('{{user}}')) return match;
        return '';
    });

    // 3. Remove common technical headers/footers often generated by models
    const technicalPatterns = [
        /^\*\*Crafting Greetings Refined\*\*/gi,
        /^\*\*Updated Character JSON\*\*/gi,
        /^\*\*JSON Update:\*\*/gi,
        /^Here is the updated JSON:*/gi,
        /^Assistant Persona:*/gi,
        /^Task: Generate*/gi
    ];

    technicalPatterns.forEach(pattern => {
        cleaned = cleaned.replace(pattern, '');
    });

    // 4. Cleanup whitespace
    cleaned = cleaned.trim();

    // 5. Fallback if the message became empty (e.g., AI sent ONLY JSON)
    if (!cleaned && content.includes('```json')) {
        return "I've updated the character data for you! ✨";
    }

    return cleaned || content;
};
